sudo: required
services: 
  -docker

before_install: 
  - docker build -t tempbuild -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true tempbuild npm test

after_success: 
  - docker build -t bloodjes/multi-client ./client
  - docker build -t bloodjes/multi-nginx ./nginx
  - docker build -t bloodjes/multi-server ./server
  - docker build -t bloodjes/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push bloodjes/multi-client
  - docker push bloodjes/multi-nginx
  - docker push bloodjes/multi-server
  - docker push bloodjes/multi-worker

deploy: 
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: docker-multi
  env: DockerMulti-env
  bucket_name: elasticbeanstalk-us-east-2-947838407953
  bucket_path: docker-multi
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
